CREATE TABLE [dbo].[TM_HISTORY_APP_SETTING_CONFIG_VERSION] (
    [HSV_ID]      INT             IDENTITY (1, 1) NOT NULL,
    [HSV_VERSION] DECIMAL (10, 2) NOT NULL,
    [HSV_CST_ID] INT  NOT NULL, 
    [HSV_UPDATED_AT] DATETIME NOT NULL DEFAULT GETDATE(), 
    [HSV_UPDATED_BY] VARCHAR(256) NOT NULL DEFAULT CURRENT_USER, 
    [HSV_ASV_ID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([HSV_ID] ASC), 
    CONSTRAINT [FK_TM_HISTORY_APP_SETTING_CONFIG_VERSION_TS_CONFIG_SETTING_TYPE] FOREIGN KEY (HSV_CST_ID) REFERENCES [TS_CONFIG_SETTING_TYPE]([CST_ID]),
    CONSTRAINT [FK_TM_HISTORY_APP_SETTING_CONFIG_VERSION_TM_APP_SETTING_CONFIG_VERSION] FOREIGN KEY (HSV_ASV_ID) REFERENCES [TM_APP_SETTING_CONFIG_VERSION]([ASV_ID]),
);


GO
