CREATE TABLE [dbo].[TM_HISTORY_APP_SETTING_CONFIG_VERSION_DEPLOY] (
    [HCD_ID]      INT             IDENTITY (1, 1) NOT NULL,
    [HCD_DEPLOYED_TIME] datetime NOT NULL  DEFAULT getdate(),  
    [HCD_ASV_ID] INT NOT NULL, 
	[HCD_IP_ADDRESS] varchar(100) NOT NULL, 
    PRIMARY KEY CLUSTERED ([HCD_ID] ASC), 
    CONSTRAINT [FK_TM_HISTORY_APP_SETTING_CONFIG_VERSION_DEPLOY_TM_APP_SETTING_CONFIG_VERSION] FOREIGN KEY (HCD_ASV_ID) REFERENCES [TM_APP_SETTING_CONFIG_VERSION]([ASV_ID])
);

GO
